create table public.confirmacoes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  telefone text,
  confirmacao_presenca text not null check (confirmacao_presenca in ('sim', 'nao')),
  quantidade integer not null default 1,
  observacao text
);

alter table public.confirmacoes enable row level security;

create policy "Permitir inserir confirmacoes publicamente"
on public.confirmacoes
for insert
to anon
with check (true);

-- Não crie política de SELECT para anon.
-- Assim, os convidados conseguem enviar, mas não conseguem ver a lista.
