create table if not exists public.confirmacoes (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nome text not null,
  telefone text,
  confirmacao_presenca text not null check (confirmacao_presenca in ('sim', 'nao')),
  quantidade integer not null default 1,
  observacao text,
  acompanhantes jsonb not null default '[]'::jsonb,
  constraint confirmacoes_acompanhantes_array check (jsonb_typeof(acompanhantes) = 'array')
);

alter table public.confirmacoes
add column if not exists acompanhantes jsonb not null default '[]'::jsonb;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'confirmacoes_acompanhantes_array'
  ) then
    alter table public.confirmacoes
    add constraint confirmacoes_acompanhantes_array
    check (jsonb_typeof(acompanhantes) = 'array');
  end if;
end $$;

alter table public.confirmacoes enable row level security;

create table if not exists public.admin_usuarios (
  email text primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.admin_usuarios enable row level security;

grant insert on table public.confirmacoes to anon, authenticated;
grant select on table public.confirmacoes to authenticated;

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.admin_usuarios
    where lower(email) = lower(auth.jwt() ->> 'email')
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

drop policy if exists "Permitir inserir confirmacoes publicamente" on public.confirmacoes;
create policy "Permitir inserir confirmacoes publicamente"
on public.confirmacoes
for insert
to anon, authenticated
with check (true);

drop policy if exists "Permitir leitura para administradores" on public.confirmacoes;
create policy "Permitir leitura para administradores"
on public.confirmacoes
for select
to authenticated
using (public.is_admin());

-- Depois de criar seu usuário em Authentication > Users, libere o e-mail admin:
-- insert into public.admin_usuarios (email)
-- values ('seu-email@exemplo.com')
-- on conflict (email) do nothing;

-- Não crie política de SELECT para anon. Assim, os convidados conseguem enviar,
-- mas não conseguem ver a lista de confirmações.
